### ISSUE TITLE
Now I find that the latest version needs a new certificate supplied. The current one causes a failure.

### ISSUE THREAD

**Issue by DoctorWho8** [MahStudio/WSLackware#16]
Hello!
I needed to redo Windows entirely here. Trying to install things by clicking on the App blob cause it to fail with this message:
"This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)" I've seen it happen before whilst still using the Powershell scripts supplied here.

**Comment by RezaT4795** [comment]
@DoctorWho8 That's because you're sideloading the package and you haven't installed the certificate included in the zip file.
Try importing the .cer file to "Trusted Root" first and then install the package again.

**Comment by RezaT4795** [comment]
@DoctorWho8  That's because you're sideloading the package and you haven't installed the certificate included in the zip file.
Try importing the .cer file to "Trusted Root" first and then install the package again.
We're gonna publish WSLackware on Microsoft Store soon, and these kind of issues won't happen again.
